import React, { useMemo, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, OrthographicCamera, Text } from "@react-three/drei";

const COLORS = {
  brickRed: "#C1440E",
  brickOrange: "#E9854A",
  cream: "#F5E6C8",
  creamDark: "#E9D0A8",
  charcoal: "#3D2B1F",
  sage: "#8FAF76",
  sageDark: "#5F7E4D",
  mortar: "#F4D9B7",
  firebrick: "#A8321A",
  cutBrick: "#F2A35E",
  vent: "#6B7C85",
  cleanout: "#8B5E3C",
  foundation: "#B8A38D",
  skyCream: "#FFF7E8",
  gridLine: "rgba(61,43,31,0.18)"
};

const translations = {
  ru: {
    appTitle: "Печь по порядовкам",
    projectName: "Ручная раскладка печника",
    reset: "Сброс",
    language: "Язык",
    parametersTab: "Параметры",
    builderTab: "Кладка",
    parametersTitle: "Параметры мастерской",
    parametersSubtitle: "Задайте габариты. Они влияют на сетку, высоту и расчёт материалов.",
    foundationWidthTitle: "Ширина основания",
    foundationWidthHelp: "Ширина рабочей зоны печи в сантиметрах.",
    foundationLengthTitle: "Длина основания",
    foundationLengthHelp: "Длина рабочей зоны печи в сантиметрах.",
    foundationThicknessTitle: "Толщина фундамента",
    foundationThicknessHelp: "Толщина бетонной плиты.",
    roomHeightTitle: "Высота помещения",
    roomHeightHelp: "От верха фундамента до потолка.",
    looksBuildable: "Параметры пригодны",
    checkDimensions: "Проверьте размеры",
    validationHeight: "Полезная высота меньше 190 см. Для демонстрационной кладки это слишком мало.",
    validationFootprint: "Основание слишком вытянуто. Лучше держать пропорции ближе к реальной печи.",
    validationOk: "Можно раскладывать порядовку вручную.",
    startBuild: "Перейти к раскладке",
    editorTitle: "Редактор порядовки",
    editorSubtitle: "Выберите ряд, инструмент и ставьте кирпичи по сетке. 3D построен на Three.js, кирпичи привязаны к той же сетке.",
    rowsRail: "Ряды",
    currentRow: "Ряд",
    addRow: "+ ряд",
    copyPrev: "Копия",
    clearRow: "Очистить",
    completeRow: "Зафиксировать",
    rowCompleted: "Готово",
    tools: "Инструменты",
    orientation: "Ориентация",
    horizontal: "Гориз.",
    vertical: "Вертик.",
    viewMode: "Вид",
    view2d: "2D",
    view3d: "3D",
    paletteHint: "Тап по сетке ставит или заменяет кирпич. Ластик удаляет.",
    standard: "Кирпич",
    cut: "Половинка",
    firebrick: "Шамот",
    vent: "Канал",
    cleanout: "Дверца",
    eraser: "Ластик",
    materialsSnapshot: "Материалы",
    regularBricks: "Обычный кирпич",
    firebricks: "Шамот",
    cutBricks: "Подрезки",
    mortarEstimate: "Раствор",
    foundationConcrete: "Бетон",
    totalPlaced: "Уложено",
    ceilingLimit: "потолок",
    liveSidePreview: "Силуэт",
    gridLabel: "Сетка кладки",
    brickSize: "кирпич 250×120",
    camera: "Камера",
    zoomIn: "+",
    zoomOut: "−",
    rotateLeft: "↺",
    rotateRight: "↻",
    resetCamera: "Сброс",
    zoom: "Масштаб",
    angle: "Угол",
    dragHint: "В 3D: перетаскивание — вращение, колесо/пинч — масштаб, правый drag — сдвиг.",
    true3d: "Three.js",
    alignedGrid: "ячейка 12.5 см",
    ariaPlan: "План ряда печной кладки",
    aria3d: "3D порядовка с размерной сеткой"
  },
  en: {
    appTitle: "Brick Stove Order Builder",
    projectName: "Manual Stove Layout Studio",
    reset: "Reset",
    language: "Language",
    parametersTab: "Parameters",
    builderTab: "Masonry",
    parametersTitle: "Workshop parameters",
    parametersSubtitle: "Set base and room dimensions. They drive grid size, height and material estimates.",
    foundationWidthTitle: "Base width",
    foundationWidthHelp: "Working stove footprint width in centimeters.",
    foundationLengthTitle: "Base length",
    foundationLengthHelp: "Working stove footprint length in centimeters.",
    foundationThicknessTitle: "Foundation thickness",
    foundationThicknessHelp: "Concrete slab thickness.",
    roomHeightTitle: "Room height",
    roomHeightHelp: "From foundation top to ceiling.",
    looksBuildable: "Dimensions work",
    checkDimensions: "Check dimensions",
    validationHeight: "Usable height is under 190 cm. Too low for this demo layout.",
    validationFootprint: "The base is too stretched. Keep proportions closer to a real stove.",
    validationOk: "Ready for manual row-by-row layout.",
    startBuild: "Open layout editor",
    editorTitle: "Stove masonry editor",
    editorSubtitle: "Choose a row and a tool, then place bricks on the grid. 3D uses Three.js, so bricks snap to the same grid.",
    rowsRail: "Rows",
    currentRow: "Row",
    addRow: "+ row",
    copyPrev: "Copy",
    clearRow: "Clear",
    completeRow: "Lock",
    rowCompleted: "Done",
    tools: "Tools",
    orientation: "Orientation",
    horizontal: "Horiz.",
    vertical: "Vert.",
    viewMode: "View",
    view2d: "2D",
    view3d: "3D",
    paletteHint: "Tap the grid to place or replace a brick. Eraser removes it.",
    standard: "Brick",
    cut: "Half",
    firebrick: "Firebrick",
    vent: "Flue",
    cleanout: "Door",
    eraser: "Eraser",
    materialsSnapshot: "Materials",
    regularBricks: "Regular bricks",
    firebricks: "Firebricks",
    cutBricks: "Cuts",
    mortarEstimate: "Mortar",
    foundationConcrete: "Concrete",
    totalPlaced: "Placed",
    ceilingLimit: "ceiling",
    liveSidePreview: "Silhouette",
    gridLabel: "Masonry grid",
    brickSize: "brick 250×120",
    camera: "Camera",
    zoomIn: "+",
    zoomOut: "−",
    rotateLeft: "↺",
    rotateRight: "↻",
    resetCamera: "Reset",
    zoom: "Zoom",
    angle: "Angle",
    dragHint: "In 3D: drag rotates, wheel/pinch zooms, right-drag pans.",
    true3d: "Three.js",
    alignedGrid: "12.5 cm cell",
    ariaPlan: "Top-down stove masonry row plan",
    aria3d: "3D brick order layout with centimeter grid"
  },
  lt: {
    appTitle: "Krosnies eiliavimo kūrimas",
    projectName: "Rankinis krosnininko maketas",
    reset: "Atkurti",
    language: "Kalba",
    parametersTab: "Parametrai",
    builderTab: "Mūras",
    parametersTitle: "Dirbtuvės parametrai",
    parametersSubtitle: "Nustatykite pagrindo ir patalpos matmenis.",
    foundationWidthTitle: "Pagrindo plotis",
    foundationWidthHelp: "Darbinės krosnies zonos plotis centimetrais.",
    foundationLengthTitle: "Pagrindo ilgis",
    foundationLengthHelp: "Darbinės krosnies zonos ilgis centimetrais.",
    foundationThicknessTitle: "Pamato storis",
    foundationThicknessHelp: "Betono plokštės storis.",
    roomHeightTitle: "Patalpos aukštis",
    roomHeightHelp: "Nuo pamato viršaus iki lubų.",
    looksBuildable: "Matmenys tinka",
    checkDimensions: "Patikrinkite matmenis",
    validationHeight: "Naudingas aukštis mažesnis nei 190 cm. Šiam maketui per mažai.",
    validationFootprint: "Pagrindas per daug ištęstas.",
    validationOk: "Galima rankiniu būdu dėlioti eiles.",
    startBuild: "Atidaryti redaktorių",
    editorTitle: "Krosnies mūro redaktorius",
    editorSubtitle: "Pasirinkite eilę ir įrankį, tada dėkite plytas ant tinklelio.",
    rowsRail: "Eilės",
    currentRow: "Eilė",
    addRow: "+ eilė",
    copyPrev: "Kopija",
    clearRow: "Valyti",
    completeRow: "Užrakinti",
    rowCompleted: "Baigta",
    tools: "Įrankiai",
    orientation: "Kryptis",
    horizontal: "Horiz.",
    vertical: "Vert.",
    viewMode: "Vaizdas",
    view2d: "2D",
    view3d: "3D",
    paletteHint: "Bakstelėkite tinklelį, kad padėtumėte arba pakeistumėte plytą.",
    standard: "Plyta",
    cut: "Pusė",
    firebrick: "Šamotinė",
    vent: "Kanalas",
    cleanout: "Durelės",
    eraser: "Trintukas",
    materialsSnapshot: "Medžiagos",
    regularBricks: "Paprastos plytos",
    firebricks: "Šamotinės plytos",
    cutBricks: "Pjautos",
    mortarEstimate: "Skiedinys",
    foundationConcrete: "Betonas",
    totalPlaced: "Sudėta",
    ceilingLimit: "lubos",
    liveSidePreview: "Siluetas",
    gridLabel: "Mūro tinklelis",
    brickSize: "plyta 250×120",
    camera: "Kamera",
    zoomIn: "+",
    zoomOut: "−",
    rotateLeft: "↺",
    rotateRight: "↻",
    resetCamera: "Atkurti",
    zoom: "Mastelis",
    angle: "Kampas",
    dragHint: "3D: tempimas suka, ratukas/pinch priartina.",
    true3d: "Three.js",
    alignedGrid: "12.5 cm langelis",
    ariaPlan: "Viršutinis mūro eilės planas",
    aria3d: "3D eiliavimo maketas su cm tinkleliu"
  }
} as const;

type Locale = keyof typeof translations;

export default function BrickStoveLayoutStudio() {
  const [locale] = useState<Locale>("ru");
  const t = (key: keyof typeof translations.ru) => translations[locale][key] ?? translations.ru[key];

  return (
    <div>
      <h1>{t("appTitle")}</h1>
      <p>{t("projectName")}</p>
      <Canvas>
        <OrthographicCamera makeDefault position={[6.8, 6.2, 7.2]} zoom={52} />
        <OrbitControls enableDamping dampingFactor={0.12} enableRotate enableZoom enablePan />
        <Text position={[0, 0, 0]}>{t("true3d")}</Text>
      </Canvas>
    </div>
  );
}
